CREATE DATABASE MySQLDB LOG TEST;
USE MySQLDB LOG TEST;
CREATE TABLE STUDENT (
	StudentName VARCHAR(1),
	StudentSSN INT DEFAULT 123456789,
CONSTRAINT STUDENT_PK PRIMARY KEY (StudentSSN)
);

CREATE TABLE COURSES (
	Grade VARCHAR(1),
	Number VARCHAR(1),
);

CREATE TABLE FACULTY (
	FacultyName VARCHAR(1),
	FacSSN VARCHAR(1),
CONSTRAINT FACULTY_FK1 FOREIGN KEY(FacSSN) REFERENCES COURSES(Number)
);


