CREATE DATABASE MySQLDB;
USE MySQLDB;
CREATE TABLE STUDENT (
	StudentName VARCHAR(50) NOT NULL,
	StudentSSN VARCHAR(9) NOT NULL DEFAULT 123456789,
CONSTRAINT STUDENT_PK PRIMARY KEY (StudentSSN)
);

CREATE TABLE FACULTY (
	FacultyName VARCHAR(1),
	FacSSN VARCHAR(1),
);

CREATE TABLE COURSES (
	Grade VARCHAR(1),
	Number VARCHAR(1),
);

=======
DROP DATABASE IF EXISTS MySQLDB;
CREATE DATABASE MySQLDB;
USE MySQLDB;
CREATE TABLE STUDENT (
	StudentSSN VARCHAR(9),
	StudentName VARCHAR(20)
CONSTRAINT STUDENT_PK PRIMARY KEY (StudentSSN)
);

CREATE TABLE FACULTY (
	FacultyName VARCHAR(20),
	FacSSN VARCHAR(1)
CONSTRAINT FACULTY_PK PRIMARY KEY (FacultyName)
);

CREATE TABLE COURSES (
	Grade DOUBLE,
	Number VARCHAR(3)
);
