DROP DATABASE IF EXISTS MySQLDB;
CREATE DATABASE MySQLDB;
USE MySQLDB;
CREATE TABLE STUDENT (
	StudentSSN VARCHAR(9),
	StudentName VARCHAR(20)
CONSTRAINT STUDENT_PK PRIMARY KEY (StudentSSN)
);

CREATE TABLE FACULTY (
	FacultyName VARCHAR(20),
	FacSSN VARCHAR(1)
CONSTRAINT FACULTY_PK PRIMARY KEY (FacultyName)
);

CREATE TABLE COURSES (
	Grade DOUBLE,
	Number VARCHAR(3)
);


